@extends('layouts.public.landing')
@push('title', 'Inicio')
@section('content')
@include('components.public.header',['sedes'=>'#sedes'])
@include('components.public.banner')
@include('components.public.section-tenis')
@include('components.public.activity-start')
@include('components.public.campus')
@include('components.public.trainers')
@include('components.public.promises')
@include('components.public.news')
@include('components.public.footer')
@include('components.public.fixed')
@endsection
